const { startCase, camelCase, uniq, omit } = require('lodash');
const fg = require('fast-glob');
const path = require('upath');
const fs = require('fs');

// Functions

const getComponents = (type) => {
	return uniq(
		fg.sync([path.join(__dirname, `../src/components/${type}/*/component/*.tsx`)]).map((file) => {
			const parts = file.split(`components/${type}/`);
			return (parts[1] || '').split('/')[0] || null;
		})
	).map((component) => ({
		name: startCase(camelCase(component.replace(`${type}-`, ''))),
		value: component
	}));
};

const getThemesList = () => {
	return fs.readdirSync(path.join(__dirname, `../src/themes`));
};

const getImportPath = (paths) => {
	return paths
		.map((path) => {
			const fragments = path.split('/components/');
			return (fragments[1] && fragments[1].replace('.scss', '')) || null;
		})
		.filter((path) => !!path);
};

const updateThemes = () => {
	const themes = getThemesList()?.filter((theme) => theme !== '.DS_Store') || [];
	themes.forEach((theme) => {
		const themeIndexFile = path.join(__dirname, `../src/themes/${theme}/components/_index.scss`);
		try {
			if (fs.existsSync(themeIndexFile)) {
				fs.unlinkSync(themeIndexFile);
			}
		} catch (error) {
			console.error(error);
		}
		const themeComponents = getImportPath(fg.sync([path.join(__dirname, `../src/themes/${theme}/components/**/*.scss`)]));
		const wstream = fs.createWriteStream(themeIndexFile, { encoding: 'utf8' });
		wstream.write(`/**
   *@description: This file was autogenerated, don't edit!!!!
**/

`);
		themeComponents.forEach((path) => {
			wstream.write(`@forward '${path}';\n`);
		});
		wstream.end();
	});
	return themes.length > 1 ? `${themes.join(',')} themes were updated` : `${themes.join(',')} theme was updated`;
};

const updatePlaygrounds = () => {
	const playgrounds = fs.readdirSync(path.join(__dirname, `../src/playgrounds`));

	let wstream = fs.createWriteStream(path.join(__dirname, '../src/docs/playgrounds.stories.mdx'), {
		encoding: 'utf8'
	});
	wstream.write(`
[//]: # (This file was autogenerated, don't edit!!!!)

import { Meta } from "@storybook/addon-docs";

# Playgrounds

<Meta title="Documentation/Playgrounds" />

---
`);
	wstream.write(`\n<ul>\n`);
	playgrounds.forEach((playground) => {
		wstream.write(`\t<li>\n`);
		wstream.write(`\t\t<a href="playgrounds/${playground}/index.html" target="_blank">${startCase(camelCase(playground))}</a>\n`);
		wstream.write('\t</li>\n');
	});
	wstream.write('</ul>\n');
	wstream.end();
};

const COMPONENTS_TSCONFIG_PATHS = {
	atoms: {
		include: ['src/components/atoms/**/*', 'src/components/ui-v2/**/*'],
		exclude: ['src/components/molecules/**/*', 'src/components/organisms/**/*', 'src/components/ui/**/*']
	},
	molecules: {
		include: ['src/components/atoms/**/*', 'src/components/ui-v2/**/*', 'src/components/molecules/**/*'],
		exclude: ['src/components/organisms/**/*', 'src/components/ui/**/*']
	},
	organisms: {
		include: ['src/components/ui-v2/**/*', 'src/components/atoms/**/*', 'src/components/molecules/**/*', 'src/components/organisms/**/*'],
		exclude: ['src/components/ui/**/*']
	},
	apps: {
		include: [
			'src/components/ui-v2/**/*',
			'src/components/atoms/**/*',
			'src/components/molecules/**/*',
			'src/components/organisms/**/*',
			'src/components/ui/**/*',
			'src/components/ecmv/**/*',
			'src/components/apps/**/*'
		],
		exclude: []
	},
	all: {
		include: ['src'],
		exclude: []
	}
};

// Methods export

module.exports = {
	getThemesList,
	updateThemes,
	updatePlaygrounds,
	getComponents,
	COMPONENTS_TSCONFIG_PATHS
};
