const webfontConfig = require('../webfonts');
const { last } = require('lodash');
const fg = require('fast-glob');
const path = require('upath');
const fs = require('fs');

const files = fg.sync(['src/assets/icons/*.svg', '!src/assets/icons/OLD_*.svg']);
const icons = files.map(file => {
	const name = last(file.split('/')).replace('.svg', '');
	const parts = name.split('_');
	const code = parts[0];
	parts.shift();
	return {
		code,
		name: parts.join('_')
	}
});

const className = getClassName();

let wstream = fs.createWriteStream(path.join(__dirname, '../src/docs/icons.stories.mdx'), { encoding: 'utf8' });
wstream.write(`
[//]: # (This file was autogenerated, don't edit!!!!)

import { Meta } from "@storybook/addon-docs";

# Icons

<Meta title='Documentation/Icons' />
`);
wstream.write(`\n<div style={{padding: '0', display: 'flex', 'flexDirection': 'row', 'flexWrap': 'wrap'}}>\n`);
order(icons, 'code').forEach(icon => {
	const {code, name} = icon;
	wstream.write(`\t<div style={{'margin': '20px', padding: '0', display: 'flex', 'flexDirection': 'column', 'justifyContent': 'center', 'fontSize': '0.875rem', 'justifyItems': 'center', 'alignContent': 'center', 'alignItems': 'center', 'flex': '20%', 'maxWidth': 'calc(25% - 40px)', 'borderRadius': '4px', 'background': '#f9f9f9', 'color': '#4a545f'}}>\n`);
	wstream.write(`\t\t<span style={{'padding': '10px 0', 'width': '100%', 'textAlign': 'center', 'background': '#f3f2f2', 'fontSize': '0.75rem', 'display': 'flex','justify-content': 'center','align-items': 'center'}}>${code}</span>\n`);
	wstream.write(`\t\t<div style={{'flex': '1 1 100%', 'min-height': '120px', 'width': '100%', 'padding': '10px', 'display': 'flex', 'justify-content': 'center', 'align-items': 'center'}}><i style={{'font-size': '50px'}} className='${className}-${name}'></i></div>\n`);
	wstream.write(`\t\t<span style={{ 'padding': '10px 0', 'width': '100%', 'textAlign': 'center', 'background': '#f3f2f2', 'fontSize': '0.75rem', 'min-height': '50px', 'display': 'flex','justify-content': 'center','align-items': 'center'}}>${className}-${name}</span>\n`);
	wstream.write(`\t\t<span style={{'padding': '10px 0', 'width': '100%', 'textAlign': 'center', 'background': '#f3f2f2', 'fontSize': '0.75rem', 'min-height': '50px', 'display': 'flex','justify-content': 'center','align-items': 'center'}}>--theme-scib-icon-${name}</span>\n`);
	wstream.write('\t</div>\n');
});
wstream.write('</div>\n');
wstream.end();



// Functions
function getClassName() {
	return (webfontConfig && webfontConfig.templateClassName) || 'icon';
}

function order(list, key){
	return list.sort( (a, b) => {
		if(key){
			a = a[key];
			b = b[key];
		}
		if (a < b) {
		  return -1;
		}
		if (a > b) {
		  return 1;
		}
		return 0;
	  });
}
