const webfontConfig = require('../webfonts');
const { last } = require('lodash');
const fg = require('fast-glob');
const path = require('upath');
const fs = require('fs');

const files = fg.sync([path.join(__dirname, '../src/assets/icons/OLD_*.svg')]);
const icons = files.map(file => {
	return last(file.split('/')).replace('.svg', '').replace('OLD_', '');
});

const className = getClassName();

let wstream = fs.createWriteStream(path.join(__dirname, '../src/docs/icons_old.stories.mdx'), { encoding: 'utf8' });
wstream.write(`
[//]: # (This file was autogenerated, don't edit!!!!)

import { Meta } from "@storybook/addon-docs";

# Icons

<Meta title='Documentation/Icons (DEPRECATED)' />
`);
wstream.write(`\n<div style={{padding: '0', display: 'flex', 'flexDirection': 'row', 'flexWrap': 'wrap'}}>\n`);
order(icons).forEach(icon => {
	wstream.write(`\t<div style={{'margin': '20px', padding: '20px 0 0', display: 'flex', 'flexDirection': 'column', 'justifyContent': 'center', 'fontSize': '0.875rem', 'justifyItems': 'center', 'alignContent': 'center', 'alignItems': 'center', 'flex': '20%', 'maxWidth': 'calc(20% - 40px)', 'borderRadius': '4px', 'background': '#f9f9f9', 'color': '#4a545f'}}>\n`);
	wstream.write(`\t\t<i className='${className}-${icon}'></i>\n`);
	wstream.write(`\t\t<span style={{'marginTop': '20px', 'padding': '10px 0', 'width': '100%', 'textAlign': 'center', 'background': '#f3f2f2', 'fontSize': '0.75rem'}}>${className}-${icon}</span>\n`);
	wstream.write(`\t\t<span style={{'padding': '10px 0', 'width': '100%', 'textAlign': 'center', 'background': '#f3f2f2', 'fontSize': '0.75rem'}}>--theme-scib-icon-${icon}</span>\n`);
	wstream.write('\t</div>\n');
});
wstream.write('</div>\n');
wstream.end();

// Functions
function getClassName() {
	return (webfontConfig && webfontConfig.templateClassName) || 'icon';
}

function order(list, key){
	return list.sort( (a, b) => {
		if(key){
			a = a[key];
			b = b[key];
		}
		if (a < b) {
		  return -1;
		}
		if (a > b) {
		  return 1;
		}
		return 0;
	  });
}
