const { last } = require('lodash');
const fg = require('fast-glob');
const path = require('upath');
const fs = require('fs');

const files = fg.sync([path.join(__dirname, '../src/assets/images/*')]);
const images = files.map((file) => {
	return last(file.split('/'));
});

let wstream = fs.createWriteStream(path.join(__dirname, '../src/docs/images.stories.mdx'), { encoding: 'utf8' });
wstream.write(`
[//]: # (This file was autogenerated, don't edit!!!!)

import { Meta } from "@storybook/addon-docs";

# Images

<Meta title='Documentation/Images' />
`);
wstream.write(`\n<div style={{padding: '0', display: 'flex', 'flexDirection': 'row', 'flexWrap': 'wrap'}}>\n`);
images.forEach((images) => {
	wstream.write(
		`\t<div style={{'margin': '20px', padding: '20px 0 0', display: 'flex', 'flexDirection': 'column', 'justifyContent': 'center', 'fontSize': '0.875rem', 'justifyItems': 'center', 'alignContent': 'center', 'alignItems': 'center', 'flex': '20%', 'maxWidth': 'calc(33% - 40px)', 'borderRadius': '4px', 'background': '#f9f9f9', 'color': '#4a545f'}}>\n`
	);
	wstream.write(`\t\t<img style={{'width': '150px', 'height': '130px'}} src="assets/images/${images}"></img>\n`);
	wstream.write(
		`\t\t<span style={{'marginTop': '20px', 'padding': '10px 0', 'width': '100%', 'textAlign': 'center', 'background': '#f3f2f2'}}>${images}</span>\n`
	);
	wstream.write('\t</div>\n');
});
wstream.write('</div>\n');
wstream.end();

const files_color_icons = fg.sync([path.join(__dirname, '../src/assets/color_icons/*')]);
const icons = files_color_icons.map((file) => {
	return last(file.split('/'));
});

let wstream_icons = fs.createWriteStream(path.join(__dirname, '../src/docs/color_icons.stories.mdx'), { encoding: 'utf8' });
wstream_icons.write(`
[//]: # (This file was autogenerated, don't edit!!!!)

import { Meta } from "@storybook/addon-docs";

# Color Icons

<Meta title='Documentation/Color Icons' />
`);
wstream_icons.write(`\n<div style={{padding: '0', display: 'flex', 'flexDirection': 'row', 'flexWrap': 'wrap'}}>\n`);
icons.forEach((images) => {
	wstream_icons.write(
		`\t<div style={{'margin': '20px', padding: '20px 0 0', display: 'flex', 'flexDirection': 'column', 'justifyContent': 'center', 'fontSize': '0.875rem', 'justifyItems': 'center', 'alignContent': 'center', 'alignItems': 'center', 'flex': '20%', 'maxWidth': 'calc(33% - 40px)', 'borderRadius': '4px', 'background': '#f9f9f9', 'color': '#4a545f'}}>\n`
	);
	wstream_icons.write(`\t\t<img style={{'width': '150px', 'height': '130px'}} src="assets/color_icons/${images}"></img>\n`);
	wstream_icons.write(
		`\t\t<span style={{'marginTop': '20px', 'padding': '10px 0', 'width': '100%', 'textAlign': 'center', 'background': '#f3f2f2'}}>${images.replace(
			'.svg',
			''
		)}</span>\n`
	);
	wstream_icons.write('\t</div>\n');
});
wstream_icons.write('</div>\n');
wstream_icons.end();
